# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "nrf52840"

[matrix]
matrix_type = "direct_pin"

# 2D array representing your direct-pin matrix
direct_pins = [
    ["PIN_1","_","_"],
    ["_","PIN_1","PIN_1"],
    ["PIN_1","PIN_1","PIN_1"],
    ["PIN_1","PIN_1","PIN_1"],
    ["PIN_1","PIN_1","PIN_1"],
    ["PIN_1","PIN_1","PIN_1"],
]

# Pin behavior (default: true = active low with pull-up)
direct_pin_low_active = true

# Encoder 0
[[input_device.encoder]]
pin_a = "PIN_1"
pin_b = "PIN_1"
phase = "resolution"
resolution = 2
internal_pullup = true

# Encoder 1
[[input_device.encoder]]
pin_a = "PIN_1"
pin_b = "PIN_1"
phase = "resolution"
resolution = 2
internal_pullup = true

[layout]
rows = 6
cols = 3
layers = 2
keymap = [
    [
        ["A", "_", "_"],
        ["_", "B", "C"],
        ["D", "E", "F"],
        ["G", "H", "I"],
        ["J", "K", "L"],
        ["N", "M", "O"]
    ],
    [
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"]
    ]
]
