# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "KeyboardN"
product_name = "KeyboardName"
serial_number = "vial:f64c2b3c"
usb_enable = true
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "NRF"
chip = "nrf52840"

[matrix]
row_pins = [
    "P0_17",  # Win+Q
    "P0_20",  # Alt+W
    "P0_22",  # Shift+E
    "P0_24",  # Ctrl+R
    "P1_00",  # T
    "P0_31",  # 鼠标左键
    "P0_29",  # Shift+鼠标右键
    "P0_02",  # Backspace
    "P1_15",  # Enter
    "P1_13",  # Space
]
col_pins = [""]

# Encoder 0
[[input_device.encoder]]
pin_a = "P1_01"
pin_b = "P1_02"
button_pin = "P1_07"
