name: Install Rust toolchain
uses: dtolnay/rust-toolchain@master
with:
   toolchain: 1.96.0
   targets: thumbv7em-none-eabihf
   components: rust-src
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    uses: haobogu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
